cmake_minimum_required(VERSION 4.2)
project(Helmke_Library_Management_System C)

set(CMAKE_C_STANDARD 11)

include_directories(.)

add_executable(Helmke_Library_Management_System
        Book.h
        database.h
        LibraryItem.h
        Patron.h
        LibraryItem.h
        LibraryItem.h
        Patron.h
        Book.h
        database.h
        Patron.cpp
        Patron.cpp
        Patron.h)
